language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: tiddlywiki ./*wiki --build
script: tiddlywiki --version
after_success:
  - bash ./publish.sh

branches:
  only:
    - master
